### ISSUE TITLE
Add interceptor on the copy of axios

### ISSUE THREAD

**Issue by AlexZd** [Flyrell/axios-auth-refresh#114] opened 2020-09-13 18:12 UTC
Hi, I'm using your lib with nuxt.js and have some issue with interception for copy of axios.
I have a following scenario: User can create a post, during creation server can return "phone_required" or "otp_required". But inside "phone_required" flow I need to intercept "otp_required".

```js
  const authHandler = error => {...}

  const otpHandler = error => {
    const errorResponse = error.response.data.error;
    if (errorResponse) {
      switch (errorResponse.code) {
        case "phone_required":
        case "phone_not_confirmed":
          console.log("phone flow");
          //showing popup with field where user need to enter his phone number and submit, during submission he will get "otp_required" response
          break;
        case "otp_required":
          console.log("otp flow");
          //showing popup with field for OTP, where user entering OTP from SMS and getting back token, which I need to adapt for retry requests
          break;
        default:
          break;
      }
    }
    return Promise.reject(error);
  }

  createAuthRefreshInterceptor($axios, authHandler, {
    statusCodes: [401]
  });

  createAuthRefreshInterceptor($axios, otpHandler, {
    statusCodes: [422]
  });

  const axiosCopy = $axios.create();

  createAuthRefreshInterceptor(axiosCopy, authHandler, {
    statusCodes: [401]
  });

  createAuthRefreshInterceptor(axiosCopy, otpHandler, {
    statusCodes: [422]
  });
```

So, inside my main component I'm using `$axios` (global axios instance) and receiving 422 from server with "phone_required" code, interceptor working fine and I'm getting "phone_required" flow. 

In this flow I need to make some update request - if I use `$axios` - it won't work because it is paused until I resolve promise of `otpHandler`, for this purpose I created `axiosCopy` and injected it globally as well and it is working fine and performing requests. 

But in case I'm getting 422 for `axiosCopy` promise is getting stack somewhere, it is not going to interceptor and it is not going to `catch` block. If I get error with code 500 for `axiosCopy` it is going to `catch` block (because I have interceptor for 422 and 401).

How I can setup interceptor for copy also?

**Comment by Flyrell** [comment] 2020-09-15 08:57
Thank you for opening the issue.

The problem is, I haven't thought about the use case where you'd create the refresh interceptor multiple times. It has a shared storage and is therefore not possible in the current version. Will look at it and release the update in the next version.

**Comment by AlexZd** [comment] 2020-09-16 18:09
As of now (if someone will be looking for same) I did it with simple axios interceptor:
```js
function authHandler(error) {
    return new Promise((resolve, reject) => {
      // Showing login popup
      window.dispatchEvent(
        new CustomEvent("...", { detail: { resolve, reject } })
      );
    })
      .then(() => {
        // Retrying failed request
        return $axios(error.config);
      })
      .catch(() => {
        // Showing initial error if something went wrong during login flow or user closed popup
        return Promise.reject(error);
      });
  }

  $axios.interceptors.response.use(
    response => response,
    error => {
      const statusCode = parseInt(error.response.status);
      switch (statusCode) {
        case 401:
          return authHandler(error);
        case 422:
          return otpHandler(error); //similar to authHandler
        default:
          return Promise.reject(error);
      }
    }
  );
```
But it does not have a feature of storing requests and retry all of them - it just retry failed requests (but in my case it is enough). And also it has a loop of interception, but in my case there is popup in the refresh login, it will prevent hidden loop :)

**Comment by Flyrell** [comment] 2020-09-17 07:46
@AlexZd Great, thanks for the help. Much appreciated.

**Comment by calluna18** [comment] 2020-10-02 11:33
So I cannot not currently use this package if:
- I have two different axios instances (same refresh logic but different base URLs)
- The app need to store and retry multiple parallell requests from both instances on 401

Is that correct or am I misunderstanding?

Thanks! 😊

**Comment by Flyrell** [comment] 2020-10-02 11:35
@calluna18 Unfortunately, yes. I'm preparing to release the v3.1.0 at the end of the next week, which will support these scenarios, but for now there's no possibility to do that 😞

**Comment by calluna18** [comment] 2020-10-02 12:04
@Flyrell Ok, thanks a lot for a quick response! 😌

**Comment by tleclaire** [comment] 2020-10-08 06:21
Any news on this? I could make good use of this functionallity as well. ;-)

**Comment by Flyrell** [comment] 2021-01-12 08:54
Will publish the changes in the upcoming v3.1.0.
I don't want to promise when it'd be done, as I'm having a busy time right now, but I hope it will be soon. Thanks for understanding.

**Comment by annazus** [comment] 2021-05-18 22:46
@Flyrell First of all thank you for such a well documented and easy to use package.  This is a follow-up to calluna18's question above.  I have the same requirement - multiple axios instances with different base urls.  The app needs to store and retry multiple parallel requests from both instances on 401.  Is this feature currently available in v3.1.0?

**Comment by calluna18** [comment] 2021-09-14 16:12
Hi @Flyrell! I see there has been a merged PR for this issue. Will there be a new release with this fix anytime soon? 🙂  Thanks!

**Comment by Flyrell** [comment] 2021-09-16 20:04
Hi @calluna18 sorry for this huuuge delay 😄  It's published now 🥳 🎉

**Closed by Flyrell** 2021-09-16 20:04 UTC
Labels: bug

**Comment by calluna18** [comment] 2021-09-17 11:42
Awesome, thanks! 🤩  Will try it out! 🙏
