### ISSUE TITLE
Bump Axios peerDependencies to ~0.21.1

### ISSUE THREAD

**Issue by HaralayyaS-ELS-CT** [Flyrell/axios-auth-refresh#144] opened 2021-02-02 00:11 UTC
@Flyrell Axios v0.21.1 is released. Can we get peerDependency to `~0.21.1`? Related to #75

**Comment by Flyrell** [comment] 2021-02-02 07:04
Duplicate of #143. I'm going to release it in few minutes.

**Closed by Flyrell** 2021-02-02 07:04 UTC
