### ISSUE TITLE
Interceptor order.

### ISSUE THREAD

**Issue by deguich** [Flyrell/axios-auth-refresh#28] opened 2019-10-04 14:43 UTC
Hi, first, thx for this usefull module.

Could be better to disable interceptor and re-enable it without using axios "eject / use" function.
Axios "eject / use" function break the interceptor order. 
So, first time, my interceptor is well called after refresh.
Second time, my interceptor is called before refresh (and refresh is called if my interceptor reject the promise with the original error).
Perhaps using a flag or other trick could help ...

**Comment by Flyrell** [comment] 2019-10-11 08:41
Hi @deguich,
thanks for submitting the issue and sorry for the late response. This should now be fixed in v2.0.0-beta.2.
You can try it out `npm install axios-auth-refresh@beta` and the updated docs are already in #27.

Would you please try it and give me the feedback? Thank you.

**Comment by Flyrell** [comment] 2019-10-11 08:42
I will close the issue as it's a duplicate of #12, let move it there please.

**Closed by Flyrell** 2019-10-11 08:42 UTC
Labels: bug, good first issue, looking for beta testers, waiting
