### ISSUE TITLE
Docs improvement on usage section

### ISSUE THREAD

**Issue by jacklimwenjie** [Flyrell/axios-auth-refresh#164] opened 2021-07-23 11:52 UTC
The "Syntax" section states that the `createAuthRefreshInterceptor` returns the interceptor ID so that we could eject if needed.

However, later on in the "Usage" section, the code snippet states that 

> // Instantiate the interceptor (you can chain it as it returns the axios instance)

Without reading the "Syntax" section, this could be misleading as it suggests that we could chain axios method to the call of `createAuthRefreshInterceptor`, which is incorrect.

**Comment by Flyrell** [comment] 2021-09-16 18:47
Hi. Thanks for pointing that out. However, it's a duplicate of #137 so I'm closing the issue.

**Closed by Flyrell** 2021-09-16 18:47 UTC
